import { PlatformSpec } from '../types';

export const PLATFORM_SPECS: Record<string, PlatformSpec> = {
  meta: {
    id: 'meta',
    name: 'Meta / Facebook Catalog',
    description: 'Format required for Facebook & Instagram Shops and Advantage+ Dynamic Ads',
    fields: [
      { key: 'id', label: 'id', required: true, synonyms: ['id', 'sku', 'variant_id', 'product_id', 'item_id', 'code'] },
      { key: 'title', label: 'title', required: true, synonyms: ['title', 'product_name', 'name', 'product_title', 'heading'] },
      { key: 'description', label: 'description', required: true, synonyms: ['description', 'desc', 'details', 'product_description', 'body'] },
      { key: 'availability', label: 'availability', required: true, synonyms: ['availability', 'stock', 'quantity', 'stock_status', 'available', 'in_stock'] },
      { key: 'condition', label: 'condition', required: true, synonyms: ['condition', 'state', 'item_condition'] },
      { key: 'price', label: 'price', required: true, synonyms: ['price', 'product_price', 'regular_price', 'unit_price', 'amount', 'mrp'] },
      { key: 'link', label: 'link', required: true, synonyms: ['link', 'product_url', 'url', 'product_link', 'page_url'] },
      { key: 'image_link', label: 'image_link', required: true, synonyms: ['image_link', 'image_url', 'image', 'picture', 'photo', 'img'] },
      { key: 'brand', label: 'brand', required: false, synonyms: ['brand', 'vendor', 'manufacturer', 'make'] },
      { key: 'sale_price', label: 'sale_price', required: false, synonyms: ['sale_price', 'discount_price', 'offer_price', 'special_price'] },
      { key: 'item_group_id', label: 'item_group_id', required: false, synonyms: ['item_group_id', 'group_id', 'parent_id', 'style_code', 'variant_group_id'] },
      { key: 'color', label: 'color', required: false, synonyms: ['color', 'colour', 'shade'] },
      { key: 'size', label: 'size', required: false, synonyms: ['size', 'dimension', 'measurement'] },
      { key: 'gtin', label: 'gtin', required: false, synonyms: ['gtin', 'barcode', 'upc', 'ean', 'isbn'] },
      { key: 'mpn', label: 'mpn', required: false, synonyms: ['mpn', 'manufacturer_part_number', 'model_number'] },
    ],
  },
  google: {
    id: 'google',
    name: 'Google Merchant Center',
    description: 'Standard product feed specification for Google Shopping Ads & Free Listings',
    fields: [
      { key: 'id', label: 'id', required: true, synonyms: ['id', 'sku', 'variant_id', 'product_id', 'item_id'] },
      { key: 'title', label: 'title', required: true, synonyms: ['title', 'product_name', 'name', 'product_title'] },
      { key: 'description', label: 'description', required: true, synonyms: ['description', 'desc', 'details', 'body'] },
      { key: 'link', label: 'link', required: true, synonyms: ['link', 'product_url', 'url', 'product_link'] },
      { key: 'image_link', label: 'image_link', required: true, synonyms: ['image_link', 'image_url', 'image', 'picture', 'photo'] },
      { key: 'availability', label: 'availability', required: true, synonyms: ['availability', 'stock', 'quantity', 'stock_status'] },
      { key: 'price', label: 'price', required: true, synonyms: ['price', 'product_price', 'regular_price', 'amount'] },
      { key: 'condition', label: 'condition', required: false, synonyms: ['condition', 'state', 'item_condition'] },
      { key: 'brand', label: 'brand', required: false, synonyms: ['brand', 'vendor', 'manufacturer'] },
      { key: 'gtin', label: 'gtin', required: false, synonyms: ['gtin', 'barcode', 'upc', 'ean'] },
      { key: 'mpn', label: 'mpn', required: false, synonyms: ['mpn', 'model_number'] },
      { key: 'google_product_category', label: 'google_product_category', required: false, synonyms: ['google_product_category', 'category', 'product_category'] },
      { key: 'product_type', label: 'product_type', required: false, synonyms: ['product_type', 'type', 'category_tree'] },
      { key: 'sale_price', label: 'sale_price', required: false, synonyms: ['sale_price', 'discount_price', 'offer_price'] },
      { key: 'color', label: 'color', required: false, synonyms: ['color', 'colour'] },
      { key: 'size', label: 'size', required: false, synonyms: ['size'] },
      { key: 'item_group_id', label: 'item_group_id', required: false, synonyms: ['item_group_id', 'group_id', 'parent_id'] },
    ],
  },
  generic: {
    id: 'generic',
    name: 'Clean Generic CSV',
    description: 'Clean and standardize your source spreadsheet while preserving original column structure',
    fields: [
      { key: 'id', label: 'sku_id', required: true, synonyms: ['id', 'sku', 'variant_id', 'product_id'] },
      { key: 'title', label: 'product_title', required: true, synonyms: ['title', 'product_name', 'name'] },
      { key: 'description', label: 'description', required: false, synonyms: ['description', 'desc', 'details'] },
      { key: 'price', label: 'price', required: true, synonyms: ['price', 'product_price', 'regular_price'] },
      { key: 'availability', label: 'stock_availability', required: true, synonyms: ['availability', 'stock', 'quantity'] },
      { key: 'link', label: 'product_link', required: false, synonyms: ['link', 'product_url', 'url'] },
      { key: 'image_link', label: 'image_link', required: false, synonyms: ['image_link', 'image_url', 'image'] },
      { key: 'brand', label: 'brand', required: false, synonyms: ['brand', 'vendor'] },
    ],
  },
};
