import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const base='http://127.0.0.1:4188';
const output=new URL('./checks/',import.meta.url);
await fs.mkdir(output,{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1050},acceptDownloads:true,permissions:['clipboard-read','clipboard-write']});
const page=await context.newPage();
const errors=[],requests=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('request',r=>requests.push(r.url()));
try {
  await page.goto(base);
  await page.screenshot({path:new URL('desktop.png',output).pathname,fullPage:true});
  assert.equal(await page.locator('.order-card').count(),7);
  assert.match(await page.locator('.metric.accent strong').innerText(),/5,800/);
  // Sample records have no real contact destinations.
  await page.locator('[data-action="remind"]').first().click();
  assert.equal(await page.locator('#message-instagram').isVisible(),false);
  assert.equal(await page.locator('#message-whatsapp').isVisible(),false);
  await page.locator('[data-close="message-dialog"]').click();
  await page.locator('[data-action="switch"]').click();
  assert.equal(await page.locator('.order-card').count(),0);
  await page.getByRole('button',{name:'New order',exact:true}).click();
  await page.getByLabel('Customer name',{exact:true}).fill('QA Customer, "quoted"');
  await page.getByLabel('Instagram handle',{exact:true}).fill('@qa.customer');
  await page.getByLabel('What are they ordering?').fill('Custom box');
  await page.getByLabel('Quantity',{exact:true}).fill('2');
  await page.getByLabel('Price per item').fill('999.50');
  await page.getByLabel('Delivery charge').fill('100');
  await page.getByLabel('Amount received so far').fill('500');
  await page.getByLabel('Total order cost').fill('1011');
  await page.getByLabel('Details for the customer').fill('A note, with commas\nand a second line.');
  assert.match(await page.locator('#order-calculation').innerText(),/2,099/);
  assert.match(await page.locator('#order-calculation').innerText(),/549\.5/);
  await page.getByRole('button',{name:'Save order',exact:true}).click();
  await page.reload();
  assert.equal(await page.locator('.order-card').count(),1);
  assert.match(await page.locator('.order-card').innerText(),/1,599/);
  await page.getByRole('button',{name:'View quote',exact:true}).click();
  const quote=await page.locator('#quote-preview').innerText();
  assert.match(quote,/QA Customer, "quoted"/);
  assert.ok(!quote.includes('1,011')&&!quote.includes('1,088'),'Private costs must not appear in the quote');
  await page.getByRole('button',{name:'Copy text',exact:true}).click();
  const copied=await page.evaluate(()=>navigator.clipboard.readText());
  assert.match(copied,/2,099/);
  const [png]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Save image',exact:true}).click()]);
  await png.saveAs(new URL('quote.png',output).pathname);
  assert.ok((await fs.stat(new URL('quote.png',output))).size>10000);
  await page.getByRole('button',{name:'Mark quote sent',exact:true}).click();
  assert.equal(await page.locator('.lane[data-lane="quoted"] .order-card').count(),1);
  const [csv]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Export orders CSV'}).click()]);
  await csv.saveAs(new URL('orders.csv',output).pathname);
  const csvText=await fs.readFile(new URL('orders.csv',output),'utf8');
  assert.ok(csvText.includes('"QA Customer, ""quoted"""'));
  assert.ok(csvText.includes('A note, with commas\nand a second line.'));
  await page.locator('[data-nav="settings"]').click();
  await page.getByLabel('Business name',{exact:true}).fill('QA Studio');
  await page.getByRole('button',{name:'Save business details',exact:true}).click();
  const [backup]=await Promise.all([page.waitForEvent('download'),page.locator('#content [data-action="backup"]').click()]);
  await backup.saveAs(new URL('backup.json',output).pathname);
  const saved=JSON.parse(await fs.readFile(new URL('backup.json',output),'utf8'));
  assert.equal(saved.business.name,'QA Studio');
  assert.equal(saved.orders[0].paid,500);
  await page.locator('#restore-file').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{"version":1}')});
  await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('Restore failed'));
  assert.match(await page.locator('#toast').innerText(),/Restore failed/);
  await page.locator('[data-nav="orders"]').click();
  await page.getByRole('button',{name:'Open order for QA Customer'}).click();
  await page.getByLabel('Amount received so far').fill('3000');
  await page.getByRole('button',{name:'Save order',exact:true}).click();
  assert.match(await page.locator('#order-error').innerText(),/cannot exceed/);
  await page.getByLabel('Amount received so far').fill('500');
  const today=await page.evaluate(()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`});
  await page.getByLabel('Next follow-up',{exact:true}).fill(today);
  await page.getByRole('button',{name:'Save order',exact:true}).click();
  await page.locator('[data-nav="followups"]').click();
  assert.equal(await page.locator('.due-row').count(),1);
  await page.getByRole('button',{name:'Prepare message'}).click();
  assert.match(await page.locator('#message-text').inputValue(),/549\.5/);
  await page.getByRole('button',{name:'I sent it'}).click();
  assert.equal(await page.locator('.due-row').count(),0);
  // Restore a good backup into the same personal workspace.
  await page.locator('[data-nav="settings"]').click();
  await page.locator('#restore-file').setInputFiles(new URL('backup.json',output).pathname);
  await page.getByRole('button',{name:'Continue',exact:true}).click();
  await page.reload();
  assert.equal(await page.locator('.order-card').count(),1);
  await page.locator('[data-nav="settings"]').click();
  await page.getByRole('button',{name:'View sample workspace'}).click();
  assert.equal(await page.locator('.order-card').count(),7);
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:new URL('mobile.png',output).pathname,fullPage:true});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No horizontal overflow on mobile');
  await page.getByRole('button',{name:'New order',exact:true}).click();
  assert.ok(await page.evaluate(()=>document.querySelector('#order-dialog').getBoundingClientRect().right<=innerWidth));
  await page.locator('[data-close="order-dialog"]').first().click();
  await page.getByRole('button',{name:'View quote',exact:true}).first().click();
  await page.evaluate(()=>window.print=()=>{});
  await page.getByRole('button',{name:'Print / PDF'}).click();
  await page.emulateMedia({media:'print'});
  assert.equal(await page.locator('#print-root').isVisible(),true);
  assert.equal(await page.locator('.shell').isVisible(),false);
  await page.pdf({path:new URL('quote.pdf',output).pathname,format:'A4',printBackground:true});
  await page.emulateMedia({media:'screen'});
  await page.locator('[data-close="quote-dialog"]').click();
  await context.setOffline(true);
  await page.getByRole('button',{name:'New order',exact:true}).click();
  await page.getByLabel('Customer name',{exact:true}).fill('Offline customer');
  await page.getByLabel('What are they ordering?').fill('Offline order');
  await page.getByLabel('Price per item').fill('100');
  await page.getByRole('button',{name:'Save order',exact:true}).click();
  assert.equal(await page.locator('.order-card').count(),8);
  assert.deepEqual(errors,[]);
  assert.ok(requests.every(url=>url.startsWith(base)),'No third-party runtime requests');
  console.log('PASS: sample totals; own workspace; create and persist; private-cost exclusion; clipboard; PNG; CSV escaping; business settings; backup and restore; invalid backup; overpayment rejection; due follow-ups; workspace isolation; mobile; offline actions; no third-party requests or browser errors.');
} finally {await browser.close()}
